### ISSUE TITLE
Command Error

### ISSUE THREAD

**Issue by Raul125** [rby-blackruby/DocRework#2]
This causes the error: https://github.com/rby-blackruby/DocRework/blame/1.3.2/EventHandler.cs#L53

The command of your plugins works fine, but with ev.Allow = false, causes conflicts with other commands.

**Comment by rby-blackruby** [comment]
Hello,

Thank you for reaching out to me. 

Please, contact me on discord (blackruby#1489) for easier communication.

blackruby
